#!/usr/bin/env bash
#Write a Bash script that displays the content of the file /etc/passwd.
#Your script should only display:
#username
#user id
#Home directory path for the user
while IFS=: read -r user _ uid _ _ home _; do
	echo "$user:$uid:$home"
done < /etc/passwd
