#!/usr/bin/env bash
#Displays "Best School" 8 times, but after 3th, prints "bad luck" and after 8th prints "good luck"
i=1
while (( i <= 10 ))
do
	if (( i == 4 ))
	then
		echo "bad luck"
	elif (( i == 8 ))
	then
		echo "good luck"
	else 
		echo "Best School"
	fi
	((i++))
done
