#!/usr/bin/env bash
#This script shows the numbers from 1 to 20, but after 4 it indicates bad luck from China, after 9 from Japan, and after 17 from Italy.
i=1
while (( i <= 20 ))
do
	echo "$i"
	case $i in
		4)
			echo "bad luck from China"
		;;	
		9) 
			echo "bad luck from Japan"
		;;
		17)
			echo "bad luck from Italy"
		;;
	esac
	((i++))
done
