#!/usr/bin/env bash
# Process and PID file

# PID fayl
pid_file="/var/run/myscript.pid"
echo $$ > "$pid_file"

# Siqnallar
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -f "$pid_file"; exit 0' SIGQUIT SIGTERM

#loop
while true; do
    echo "To infinity and beyond"
    sleep 2
done

