#!/usr/bin/env bash
# 10-process_and_pid_file

pid_file="/var/run/myscript.pid"

# PID faylını yarat
echo $$ > "$pid_file"

# Ctrl+C üçün
trap 'echo "Y U no love me?!"' SIGINT

# pkill və ya SIGTERM üçün
trap 'echo "I hate the kill command"; rm -f "$pid_file"; exit 0' SIGTERM

# SIGQUIT üçün
trap 'rm -f "$pid_file"; exit 0' SIGQUIT

# Sonsuz döngə
while true; do
    echo "To infinity and beyond"
    sleep 2
done
